root ::= query
operator ::= sep (i"and" | i"or") sep | sep? ("&"{1,2} | "|"{1,2}) sep?
sep ::= [ \t\r\n]+
file ::= "file:" sep? word
tag ::= word
not ::= ("!" | "not:") sep? term
word ::= "\"" ([^\"] | "\\\"")+ "\"" | [^ &|()!]+
term ::= file | tag | not | "(" query ")"
query ::= sep? term (operator term)* sep?
